//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SignUp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SignUp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("easygenerator.Web.Resources.Views.Account.SignUp", typeof(SignUp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists.
        /// </summary>
        public static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be at least 7 characters long;.
        /// </summary>
        public static string BeAtLeast7CharactersLong {
            get {
                return ResourceManager.GetString("BeAtLeast7CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least one digit;.
        /// </summary>
        public static string ContainAtLeastOneDigit {
            get {
                return ResourceManager.GetString("ContainAtLeastOneDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least one lower case letter;.
        /// </summary>
        public static string ContainAtLeastOneLowerCaseLetter {
            get {
                return ResourceManager.GetString("ContainAtLeastOneLowerCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least one special character;.
        /// </summary>
        public static string ContainAtLeastOneSpecialCharacter {
            get {
                return ResourceManager.GetString("ContainAtLeastOneSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contain at least one upper case letter;.
        /// </summary>
        public static string ContainAtLeastOneUpperCaseLetter {
            get {
                return ResourceManager.GetString("ContainAtLeastOneUpperCaseLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccountTitle {
            get {
                return ResourceManager.GetString("CreateAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string EmailCaption {
            get {
                return ResourceManager.GetString("EmailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid e-mail.
        /// </summary>
        public static string EnterValidEmailMessage {
            get {
                return ResourceManager.GetString("EnterValidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and I agree to the &lt;a href=&quot;{0}&quot;&gt;Terms&lt;/a&gt; and &lt;a href=&quot;{1}&quot;&gt;Privacy&lt;/a&gt;.
        /// </summary>
        public static string LicenseAgreeCheckBoxTitle {
            get {
                return ResourceManager.GetString("LicenseAgreeCheckBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT contain whitespace character(s)..
        /// </summary>
        public static string NotContainWhitespaceCharacters {
            get {
                return ResourceManager.GetString("NotContainWhitespaceCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordCaption {
            get {
                return ResourceManager.GetString("PasswordCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet requirements.
        /// </summary>
        public static string PasswordDoesNotMeetRequirements {
            get {
                return ResourceManager.GetString("PasswordDoesNotMeetRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is strong enough.
        /// </summary>
        public static string PasswordIsStrongEnough {
            get {
                return ResourceManager.GetString("PasswordIsStrongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required to:.
        /// </summary>
        public static string PasswordRequirementsTitle {
            get {
                return ResourceManager.GetString("PasswordRequirementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpButton {
            get {
                return ResourceManager.GetString("SignUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating....
        /// </summary>
        public static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
    }
}
