using System.Collections.Generic;
using System.Linq;

namespace easygenerator.Web.Components
{
    public static class CountriesInfo
    {
        public static string GetCountryPhoneCode(string countryName)
        {
            return CountriesInfoDictionary.SingleOrDefault(i => i.Key == countryName).Value?.PhoneCode;
        }

        public static string GetCountryCode(string countryName)
        {
            return CountriesInfoDictionary.SingleOrDefault(i => i.Key == countryName).Value?.CountryCode;
        }

        public static string GetCountryName(string countryCode)
        {
            countryCode = countryCode?.ToUpper().Trim();
            return CountriesInfoDictionary.SingleOrDefault(i => i.Value.CountryCode == countryCode).Key;
        }

        private static readonly Dictionary<string, dynamic> CountriesInfoDictionary = new Dictionary<string, dynamic>()
        {
            {"Afghanistan", new { PhoneCode = "+93", CountryCode = "AF" }},
            {"Albania", new { PhoneCode = "+355", CountryCode = "AL" }},
            {"Algeria", new { PhoneCode = "+213", CountryCode = "DZ" }},
            {"Andorra", new { PhoneCode = "+376", CountryCode = "AD" }},
            {"Angola", new { PhoneCode = "+244", CountryCode = "AO" }},
            {"Antigua and Barbuda", new { PhoneCode = "+1-268", CountryCode = "AG" }},
            {"Argentina", new { PhoneCode = "+54", CountryCode = "AR" }},
            {"Armenia", new { PhoneCode = "+374", CountryCode = "AM" }},
            {"Australia", new { PhoneCode = "+61", CountryCode = "AU" }},
            {"Austria", new { PhoneCode = "+43", CountryCode = "AT" }},
            {"Azerbaijan", new { PhoneCode = "+994", CountryCode = "AZ" }},
            {"Bahamas", new { PhoneCode = "+1-242", CountryCode = "BS" }},
            {"Bahrain", new { PhoneCode = "+973", CountryCode = "BH" }},
            {"Bangladesh", new { PhoneCode = "+880", CountryCode = "BD" }},
            {"Barbados", new { PhoneCode = "+1-246", CountryCode = "BB" }},
            {"Belarus", new { PhoneCode = "+375", CountryCode = "BY" }},
            {"Belgium", new { PhoneCode = "+32", CountryCode = "BE" }},
            {"Belize", new { PhoneCode = "+501", CountryCode = "BZ" }},
            {"Benin", new { PhoneCode = "+229", CountryCode = "BJ" }},
            {"Bhutan", new { PhoneCode = "+975", CountryCode = "BT" }},
            {"Bolivia", new { PhoneCode = "+591", CountryCode = "BO" }},
            {"Bosnia and Herzegovina", new { PhoneCode = "+387", CountryCode = "BA" }},
            {"Botswana", new { PhoneCode = "+267", CountryCode = "BW" }},
            {"Brazil", new { PhoneCode = "+55", CountryCode = "BR" }},
            {"Brunei", new { PhoneCode = "+673", CountryCode = "BN" }},
            {"Bulgaria", new { PhoneCode = "+359", CountryCode = "BG" }},
            {"Burkina Faso", new { PhoneCode = "+226", CountryCode = "BF" }},
            {"Burma", new { PhoneCode = "+95", CountryCode = "MM" }},
            {"Burundi", new { PhoneCode = "+257", CountryCode = "BI" }},
            {"Côte d'Ivoire", new { PhoneCode = "+225", CountryCode = "CI" }},
            {"Cambodia", new { PhoneCode = "+855", CountryCode = "KH" }},
            {"Cameroon", new { PhoneCode = "+237", CountryCode = "CM" }},
            {"Canada", new { PhoneCode = "+1", CountryCode = "CA" }},
            {"Cape Verde", new { PhoneCode = "+238", CountryCode = "CV" }},
            {"Central African Republic", new { PhoneCode = "+236", CountryCode = "CF" }},
            {"Chad", new { PhoneCode = "+235", CountryCode = "TD" }},
            {"Chile", new { PhoneCode = "+56", CountryCode = "CL" }},
            {"China", new { PhoneCode = "+86", CountryCode = "CN" }},
            {"Colombia", new { PhoneCode = "+57", CountryCode = "CO" }},
            {"Comoros", new { PhoneCode = "+269", CountryCode = "KM" }},
            {"Congo", new { PhoneCode = "+242", CountryCode = "CG" }},
            {"Costa Rica", new { PhoneCode = "+506", CountryCode = "CR" }},
            {"Croatia", new { PhoneCode = "+385", CountryCode = "HR" }},
            {"Cuba", new { PhoneCode = "+53", CountryCode = "CU" }},
            {"Cyprus", new { PhoneCode = "+357", CountryCode = "CY" }},
            {"Czech Republic", new { PhoneCode = "+420", CountryCode = "CZ" }},
            {"Democratic Republic of the Congo", new { PhoneCode = "+243", CountryCode = "CD" }},
            {"Denmark", new { PhoneCode = "+45", CountryCode = "DK" }},
            {"Djibouti", new { PhoneCode = "+253", CountryCode = "DJ" }},
            {"Dominica", new { PhoneCode = "+1-767", CountryCode = "DM" }},
            {"Dominican Republic", new { PhoneCode = "+1-809", CountryCode = "DO" }},
            {"East Timor", new { PhoneCode = "+670", CountryCode = "TL" }},
            {"Ecuador", new { PhoneCode = "+593", CountryCode = "EC" }},
            {"Egypt", new { PhoneCode = "+20", CountryCode = "EG" }},
            {"El Salvador", new { PhoneCode = "+503", CountryCode = "SV" }},
            {"Equatorial Guinea", new { PhoneCode = "+240", CountryCode = "GQ" }},
            {"Eritrea", new { PhoneCode = "+291", CountryCode = "ER" }},
            {"Estonia", new { PhoneCode = "+372", CountryCode = "EE" }},
            {"Ethiopia", new { PhoneCode = "+251", CountryCode = "ET" }},
            {"Faroese", new { PhoneCode = "+298", CountryCode = "FO" }},
            {"Fiji", new { PhoneCode = "+679", CountryCode = "FJ" }},
            {"Finland", new { PhoneCode = "+358", CountryCode = "FI" }},
            {"France", new { PhoneCode = "+33", CountryCode = "FR" }},
            {"Gabon", new { PhoneCode = "+241", CountryCode = "GA" }},
            {"Gambia", new { PhoneCode = "+220", CountryCode = "GM" }},
            {"Georgia", new { PhoneCode = "+995", CountryCode = "GE" }},
            {"Germany", new { PhoneCode = "+49", CountryCode = "DE" }},
            {"Ghana", new { PhoneCode = "+233", CountryCode = "GH" }},
            {"Greece", new { PhoneCode = "+30", CountryCode = "GR" }},
            {"Grenada", new { PhoneCode = "+1-473", CountryCode = "GD" }},
            {"Guatemala", new { PhoneCode = "+502", CountryCode = "GT" }},
            {"Guinea", new { PhoneCode = "+224", CountryCode = "GN" }},
            {"Guinea-Bissau", new { PhoneCode = "+245", CountryCode = "GW" }},
            {"Guyana", new { PhoneCode = "+592", CountryCode = "GY" }},
            {"Haiti", new { PhoneCode = "+509", CountryCode = "HT" }},
            {"Honduras", new { PhoneCode = "+504", CountryCode = "HN" }},
            {"Hong Kong", new { PhoneCode = "+852", CountryCode = "HK" }},
            {"Hungary", new { PhoneCode = "+36", CountryCode = "HU" }},
            {"Iceland", new { PhoneCode = "+354", CountryCode = "IS" }},
            {"India", new { PhoneCode = "+91", CountryCode = "IN" }},
            {"Indonesia", new { PhoneCode = "+62", CountryCode = "ID" }},
            {"Iran", new { PhoneCode = "+98", CountryCode = "IR" }},
            {"Iraq", new { PhoneCode = "+964", CountryCode = "IQ" }},
            {"Ireland", new { PhoneCode = "+353", CountryCode = "IE" }},
            {"Isle of Man", new { PhoneCode = "+44", CountryCode = "IM" }},
            {"Israel", new { PhoneCode = "+972", CountryCode = "IL" }},
            {"Italy", new { PhoneCode = "+39", CountryCode = "IT" }},
            {"Jamaica", new { PhoneCode = "+1-876", CountryCode = "JM" }},
            {"Japan", new { PhoneCode = "+81", CountryCode = "JP" }},
            {"Jordan", new { PhoneCode = "+962", CountryCode = "JO" }},
            {"Kazakhstan", new { PhoneCode = "+7-7", CountryCode = "KZ" }},
            {"Kenya", new { PhoneCode = "+254", CountryCode = "KE" }},
            {"Kiribati", new { PhoneCode = "+686", CountryCode = "KI" }},
            {"Korea, North", new { PhoneCode = "+850", CountryCode = "KP" }},
            {"Korea, South", new { PhoneCode = "+82", CountryCode = "KR" }},
            {"Kuwait", new { PhoneCode = "+965", CountryCode = "KW" }},
            {"Kyrgyzstan", new { PhoneCode = "+996", CountryCode = "KG" }},
            {"Laos", new { PhoneCode = "+856", CountryCode = "LA" }},
            {"Latvia", new { PhoneCode = "+371", CountryCode = "LV" }},
            {"Lebanon", new { PhoneCode = "+961", CountryCode = "LB" }},
            {"Lesotho", new { PhoneCode = "+266", CountryCode = "LS" }},
            {"Liberia", new { PhoneCode = "+231", CountryCode = "LR" }},
            {"Libya", new { PhoneCode = "+218", CountryCode = "LY" }},
            {"Liechtenstein", new { PhoneCode = "+423", CountryCode = "LI" }},
            {"Lithuania", new { PhoneCode = "+370", CountryCode = "LT" }},
            {"Luxembourg", new { PhoneCode = "+352", CountryCode = "LU" }},
            {"Macau", new { PhoneCode = "+853", CountryCode = "MO" }},
            {"Macedonia", new { PhoneCode = "+389", CountryCode = "MK" }},
            {"Madagascar", new { PhoneCode = "+261", CountryCode = "MG" }},
            {"Malawi", new { PhoneCode = "+265", CountryCode = "MW" }},
            {"Malaysia", new { PhoneCode = "+60", CountryCode = "MY" }},
            {"Maldives", new { PhoneCode = "+960", CountryCode = "MV" }},
            {"Mali", new { PhoneCode = "+223", CountryCode = "ML" }},
            {"Malta", new { PhoneCode = "+356", CountryCode = "MT" }},
            {"Marshall Islands", new { PhoneCode = "+692", CountryCode = "MH" }},
            {"Mauritania", new { PhoneCode = "+222", CountryCode = "MR" }},
            {"Mauritius", new { PhoneCode = "+230", CountryCode = "MU" }},
            {"Mexico", new { PhoneCode = "+52", CountryCode = "MX" }},
            {"Micronesia", new { PhoneCode = "+691", CountryCode = "FM" }},
            {"Moldova", new { PhoneCode = "+373", CountryCode = "MD" }},
            {"Monaco", new { PhoneCode = "+377", CountryCode = "MC" }},
            {"Mongolia", new { PhoneCode = "+976", CountryCode = "MN" }},
            {"Montenegro", new { PhoneCode = "+382", CountryCode = "ME" }},
            {"Morocco", new { PhoneCode = "+212", CountryCode = "MA" }},
            {"Mozambique", new { PhoneCode = "+258", CountryCode = "MZ" }},
            {"Namibia", new { PhoneCode = "+264", CountryCode = "NA" }},
            {"Nauru", new { PhoneCode = "+674", CountryCode = "NR" }},
            {"Nepal", new { PhoneCode = "+977", CountryCode = "NP" }},
            {"Netherlands", new { PhoneCode = "+31", CountryCode = "NL" }},
            {"New Zealand", new { PhoneCode = "+64", CountryCode = "NZ" }},
            {"Nicaragua", new { PhoneCode = "+505", CountryCode = "NI" }},
            {"Niger", new { PhoneCode = "+227", CountryCode = "NE" }},
            {"Nigeria", new { PhoneCode = "+234", CountryCode = "NG" }},
            {"Norway", new { PhoneCode = "+47", CountryCode = "NO" }},
            {"Oman", new { PhoneCode = "+968", CountryCode = "OM" }},
            {"Pakistan", new { PhoneCode = "+92", CountryCode = "PK" }},
            {"Palau", new { PhoneCode = "+680", CountryCode = "PW" }},
            {"Panama", new { PhoneCode = "+507", CountryCode = "PA" }},
            {"Papua New Guinea", new { PhoneCode = "+675", CountryCode = "PG" }},
            {"Paraguay", new { PhoneCode = "+595", CountryCode = "PY" }},
            {"Peru", new { PhoneCode = "+51", CountryCode = "PE" }},
            {"Philippines", new { PhoneCode = "+63", CountryCode = "PH" }},
            {"Poland", new { PhoneCode = "+48", CountryCode = "PL" }},
            {"Portugal", new { PhoneCode = "+351", CountryCode = "PT" }},
            {"Puerto Rico", new { PhoneCode = "+1-787", CountryCode = "	PR" }},
            {"Qatar", new { PhoneCode = "+974", CountryCode = "QA" }},
            {"Romania", new { PhoneCode = "+40", CountryCode = "RO" }},
            {"Russia", new { PhoneCode = "+7", CountryCode = "RU" }},
            {"Rwanda", new { PhoneCode = "+250", CountryCode = "RW" }},
            {"São Tomé and Príncipe", new { PhoneCode = "+239", CountryCode = "ST" }},
            {"Saint Kitts and Nevis", new { PhoneCode = "+1-869", CountryCode = "KN" }},
            {"Saint Lucia", new { PhoneCode = "+1-758", CountryCode = "LC" }},
            {"Saint Vincent and the Grenadines", new { PhoneCode = "+1-784", CountryCode = "VC" }},
            {"Samoa", new { PhoneCode = "+685", CountryCode = "WS" }},
            {"San Marino", new { PhoneCode = "+378", CountryCode = "SM" }},
            {"Saudi Arabia", new { PhoneCode = "+966", CountryCode = "SA" }},
            {"Senegal", new { PhoneCode = "+221", CountryCode = "SN" }},
            {"Serbia", new { PhoneCode = "+381", CountryCode = "RS" }},
            {"Seychelles", new { PhoneCode = "+248", CountryCode = "SC" }},
            {"Sierra Leone", new { PhoneCode = "+232", CountryCode = "SL" }},
            {"Singapore", new { PhoneCode = "+65", CountryCode = "SG" }},
            {"Slovakia", new { PhoneCode = "+421", CountryCode = "SK" }},
            {"Slovenia", new { PhoneCode = "+386", CountryCode = "SI" }},
            {"Solomon Islands", new { PhoneCode = "+677", CountryCode = "SB" }},
            {"Somalia", new { PhoneCode = "+252", CountryCode = "SO" }},
            {"South Africa", new { PhoneCode = "+27", CountryCode = "ZA" }},
            {"Spain", new { PhoneCode = "+34", CountryCode = "ES" }},
            {"Sri Lanka", new { PhoneCode = "+94", CountryCode = "LK" }},
            {"Sudan", new { PhoneCode = "+249", CountryCode = "SD" }},
            {"Suriname", new { PhoneCode = "+597", CountryCode = "SR" }},
            {"Swaziland", new { PhoneCode = "+268", CountryCode = "SZ" }},
            {"Sweden", new { PhoneCode = "+46", CountryCode = "SE" }},
            {"Switzerland", new { PhoneCode = "+41", CountryCode = "CH" }},
            {"Syria", new { PhoneCode = "+963", CountryCode = "SY" }},
            {"Taiwan", new { PhoneCode = "+886", CountryCode = "TW" }},
            {"Tajikistan", new { PhoneCode = "+992", CountryCode = "TJ" }},
            {"Tanzania", new { PhoneCode = "+255", CountryCode = "TZ" }},
            {"Thailand", new { PhoneCode = "+66", CountryCode = "TH" }},
            {"Togo", new { PhoneCode = "+228", CountryCode = "TG" }},
            {"Tonga", new { PhoneCode = "+676", CountryCode = "TO" }},
            {"Trinidad and Tobago", new { PhoneCode = "+1-868", CountryCode = "TT" }},
            {"Tunisia", new { PhoneCode = "+216", CountryCode = "TN" }},
            {"Turkey", new { PhoneCode = "+90", CountryCode = "TR" }},
            {"Turkmenistan", new { PhoneCode = "+993", CountryCode = "TM" }},
            {"Tuvalu", new { PhoneCode = "+688", CountryCode = "TV" }},
            {"Uganda", new { PhoneCode = "+256", CountryCode = "UG" }},
            {"Ukraine", new { PhoneCode = "+380", CountryCode = "UA" }},
            {"United Arab Emirates", new { PhoneCode = "+971", CountryCode = "AE" }},
            {"United Kingdom", new { PhoneCode = "+44", CountryCode = "GB" }},
            {"United States of America", new { PhoneCode = "+1", CountryCode = "US" }},
            {"Uruguay", new { PhoneCode = "+598", CountryCode = "UY" }},
            {"Uzbekistan", new { PhoneCode = "+998", CountryCode = "UZ" }},
            {"Vanuatu", new { PhoneCode = "+678", CountryCode = "VU" }},
            {"Vatican City", new { PhoneCode = "+379", CountryCode = "VA" }},
            {"Venezuela", new { PhoneCode = "+58", CountryCode = "VE" }},
            {"Vietnam", new { PhoneCode = "+84", CountryCode = "VN" }},
            {"Yemen", new { PhoneCode = "+967", CountryCode = "YE" }},
            {"Zambia", new { PhoneCode = "+260", CountryCode = "ZM" }},
            {"Zimbabwe", new { PhoneCode = "+263", CountryCode = "ZW" }}
        };
    }
}