//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace easygenerator.AcceptanceTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.LearningContents = new HashSet<LearningContent>();
        }
    
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid Objective_Id { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Objective Objective { get; set; }
        public virtual ICollection<LearningContent> LearningContents { get; set; }
    }
}
