// <auto-generated />
namespace easygenerator.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddCourseCollaborators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCourseCollaborators));
        
        string IMigrationMetadata.Id
        {
            get { return "201405070854255_AddCourseCollaborators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
