// <auto-generated />
namespace easygenerator.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddLPDocuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLPDocuments));
        
        string IMigrationMetadata.Id
        {
            get { return "201601111121220_AddLPDocuments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
